//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulador_Assembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simulador_Assembler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .asm.
        /// </summary>
        internal static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; This is a comment
        ///JMP main           ; The program starts at the main function
        ///var: DB &quot;Hello World :D&quot; 
        ///
        ///print:             ; Print function
        ///    _loop:
        ///    MOV [D], [C]
        ///    INC C
        ///    INC D
        ///    CMP [C], 0
        ///    JNZ _loop
        ///    RET         ; End of the function
        ///
        ///main:
        ///    MOV D, 232
        ///    MOV C, var
        ///
        ///    CALL print 
        ///    HLT         ; End of the program.
        /// </summary>
        internal static string HolaMundo {
            get {
                return ResourceManager.GetString("HolaMundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Language ASM-D1004 - Created by Renzo Diaz
        ///MOV D, 232
        ///JMP main
        ///
        ///print:
        ///    _loop:
        ///    MOV [D], [231]
        ///    INC D
        ///    SETI 0          ;Set input in false
        ///
        ///main:
        ///    JI print        ;Jump when an input is detected
        ///    JMP main        ;Infinite loop.
        /// </summary>
        internal static string LecturaDatos {
            get {
                return ResourceManager.GetString("LecturaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Lenguaje ASM-D1004 - Created by Renzo Diaz
        ///JMP main           ; The program stars at the main function
        ///cant: DB 0          ; Count Prime Numbers
        ///
        ///FindPrimes:
        ///MOV A, 1       
        ///    _loop1:
        ///        MOV B, 1    
        ///        MOV C, 0
        ///        _loop2:
        ///            MOV [200], A
        ///            MOD [200], B    
        ///            CMP [200], 0
        ///            JNZ Multiplo
        ///                INC C
        ///            Multiplo:
        ///            INC B
        ///        MAJ B, A
        ///        JNZ _loop2
        ///        CMP C, 2
        ///        JNZ Primo
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumerosPrimos {
            get {
                return ResourceManager.GetString("NumerosPrimos", resourceCulture);
            }
        }
    }
}
